const USERS=[{id:"raphael",name:"Raphaël",role:"Médecin"},{id:"jade",name:"Jade",role:"Médecin"},{id:"victoria",name:"Victoria",role:"Médecin"}],KEY="cabinetMedicalProV2",SESSION="cabinetMedicalProSessionV2";
const today=()=>new Date().toISOString().slice(0,10),uid=()=>crypto.randomUUID(),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),fmt=d=>d?new Date(d+"T12:00").toLocaleDateString("fr-FR"):"—";
const demo={patients:[{id:"p1",first:"Lucas",last:"Martin",birth:"2012-04-12",phone:"06 00 00 00 00",blood:"O+",allergies:"Aucune connue",history:"Aucun antécédent fictif",vaccines:"À jour (simulation)",treatments:"Aucun",notes:"Patient de démonstration."},{id:"p2",first:"Emma",last:"Bernard",birth:"2011-09-03",phone:"06 11 11 11 11",blood:"A+",allergies:"Pollen",history:"Asthme fictif",vaccines:"À vérifier (simulation)",treatments:"Aucun",notes:"Dossier de démonstration."}],appointments:[{id:"a1",date:today(),time:"09:00",patient:"Lucas Martin",reason:"Consultation de suivi",doctor:"Raphaël",status:"Prévu"},{id:"a2",date:today(),time:"10:00",patient:"Emma Bernard",reason:"Contrôle",doctor:"Jade",status:"En attente"}],consultations:[],documents:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||demo,currentUser=null,page="dashboard";
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function render(){currentUser=USERS.find(u=>u.id===localStorage.getItem(SESSION));if(!currentUser)return loginScreen();document.getElementById("app").innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">✚ <span>Cabinet Médical Pro</span><small>V2 • SIMULATION FICTIVE</small></div><nav class="nav">${nav("dashboard","⌂","Tableau de bord")}${nav("patients","👥","Patients")}${nav("appointments","▣","Rendez-vous")}${nav("waiting","⏱","Salle d'attente")}${nav("consultations","🩺","Consultations")}</nav><button class="logout" onclick="logout()">↪ <span>Déconnexion</span></button></aside><main class="main"><header class="topbar"><div><h1>${titles[page]||"Cabinet"}</h1><div class="sub">Mode simulation médicale • données fictives</div></div><div class="profile"><div class="avatar">${currentUser.name[0]}</div><div><b>${esc(currentUser.name)}</b><div class="sub">${currentUser.role}</div></div></div></header><div id="content"></div></main></div>`;pageRender()}
const titles={dashboard:"Tableau de bord",patients:"Patients",appointments:"Rendez-vous",waiting:"Salle d’attente",consultations:"Consultations"};
function nav(id,i,l){return `<button class="${page===id?"active":""}" onclick="go('${id}')">${i} <span>${l}</span></button>`}
function loginScreen(){document.getElementById("app").innerHTML=`<div class="login"><div class="login-card"><div class="logo">✚</div><h1>Cabinet Médical Pro</h1><p class="sub">Version 2 — logiciel médical fictif pour votre jeu.</p><div class="notice">⚠️ Simulation uniquement. Aucune donnée réelle de santé ne doit être saisie.</div><b>Qui est le médecin ?</b><div class="users">${USERS.map(u=>`<button class="user-btn" onclick="login('${u.id}')"><div class="avatar">${u.name[0]}</div><div><b>${u.name}</b><div class="sub">${u.role}</div></div></button>`).join("")}</div></div></div>`}
function login(id){localStorage.setItem(SESSION,id);page="dashboard";render();toast("Connexion réussie")}
function logout(){localStorage.removeItem(SESSION);render()}
function go(p){page=p;render()}
function pageRender(){let c=document.getElementById("content");c.innerHTML=page==="dashboard"?dashboard():page==="patients"?patients():page==="appointments"?appointments():page==="waiting"?waiting():consultations()}
function dashboard(){let ap=data.appointments.filter(a=>a.date===today()),mine=ap.filter(a=>a.doctor===currentUser.name);return `<div class="grid"><div class="card"><div class="stat-label">Patients</div><div class="stat-value">${data.patients.length}</div></div><div class="card"><div class="stat-label">Rendez-vous aujourd’hui</div><div class="stat-value">${ap.length}</div></div><div class="card"><div class="stat-label">Consultations</div><div class="stat-value">${data.consultations.length}</div></div><div class="card"><div class="stat-label">Mes rendez-vous</div><div class="stat-value">${mine.length}</div></div></div><div class="section"><div class="section-head"><h2>Agenda du jour</h2><button class="btn" onclick="go('appointments')">Gérer l’agenda</button></div><div class="card table-wrap">${ap.length?apptTable(ap):'<div class="empty">Aucun rendez-vous aujourd’hui.</div>'}</div></div><div class="section"><div class="grid grid3"><div class="card"><h3>Nouveau patient</h3><p class="sub">Créer un dossier fictif.</p><button class="btn" onclick="patientModal()">Créer</button></div><div class="card"><h3>Nouvelle consultation</h3><p class="sub">Ouvrir une consultation.</p><button class="btn" onclick="consultModal()">Ouvrir</button></div><div class="card"><h3>Salle d’attente</h3><p class="sub">Gérer les patients arrivés.</p><button class="btn" onclick="go('waiting')">Accéder</button></div></div></div>`}
function patients(){return `<div class="section-head"><p class="sub">Dossiers médicaux fictifs</p><div class="actions"><input id="search" class="search" placeholder="Rechercher un patient..." oninput="filterPatients()"><button class="btn" onclick="patientModal()">+ Nouveau patient</button></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Naissance</th><th>Téléphone</th><th>Allergies</th><th></th></tr></thead><tbody id="rows">${patientRows(data.patients)}</tbody></table></div>`}
function patientRows(a){return a.length?a.map(p=>`<tr><td><b>${esc(p.first)} ${esc(p.last)}</b></td><td>${fmt(p.birth)}</td><td>${esc(p.phone||"—")}</td><td>${esc(p.allergies||"—")}</td><td><button class="btn secondary" onclick="openPatient('${p.id}')">Dossier</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Aucun patient.</td></tr>`}
function filterPatients(){let q=document.getElementById("search").value.toLowerCase();document.getElementById("rows").innerHTML=patientRows(data.patients.filter(p=>(p.first+" "+p.last).toLowerCase().includes(q)))}
function appointments(){return `<div class="section-head"><p class="sub">Agenda : créer, modifier et supprimer des rendez-vous.</p><button class="btn" onclick="apptModal()">+ Nouveau rendez-vous</button></div><div class="card table-wrap">${apptTable(data.appointments,true)}</div>`}
function apptTable(a,actions=false){return `<table class="table"><thead><tr><th>Date</th><th>Heure</th><th>Patient</th><th>Motif</th><th>Médecin</th><th>Statut</th>${actions?"<th>Actions</th>":""}</tr></thead><tbody>${[...a].sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).map(x=>`<tr><td>${fmt(x.date)}</td><td><b>${esc(x.time)}</b></td><td>${esc(x.patient)}</td><td>${esc(x.reason)}</td><td>${esc(x.doctor)}</td><td><span class="badge ${x.status==="En attente"?"warning-b":x.status==="Terminé"?"success":x.status==="Annulé"?"danger-b":""}">${esc(x.status||"Prévu")}</span></td>${actions?`<td><button class="btn secondary" onclick="editAppt('${x.id}')">Modifier</button> <button class="btn danger" onclick="deleteAppt('${x.id}')">Supprimer</button></td>`:""}</tr>`).join("")}</tbody></table>`}
function waiting(){let a=data.appointments.filter(x=>x.date===today()&&x.status!=="Annulé");return `<div class="section-head"><p class="sub">Patients arrivés au cabinet — simulation.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Heure</th><th>Patient</th><th>Motif</th><th>Statut</th><th>Action</th></tr></thead><tbody>${a.length?a.map(x=>`<tr><td>${esc(x.time)}</td><td><b>${esc(x.patient)}</b></td><td>${esc(x.reason)}</td><td><span class="badge">${esc(x.status)}</span></td><td><button class="btn secondary" onclick="setStatus('${x.id}','Arrivé')">Arrivé</button> <button class="btn" onclick="setStatus('${x.id}','En consultation');consultModalByName('${esc(x.patient)}')">Commencer</button> <button class="btn secondary" onclick="setStatus('${x.id}','Terminé')">Terminer</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Aucun patient dans la salle d’attente.</td></tr>`}</tbody></table></div>`}
function setStatus(id,s){let a=data.appointments.find(x=>x.id===id);if(a){a.status=s;save();render();toast("Statut mis à jour")}}
function consultations(){return `<div class="section-head"><p class="sub">Historique : modifier ou supprimer une consultation.</p><button class="btn" onclick="consultModal()">+ Nouvelle consultation</button></div><div class="card table-wrap">${data.consultations.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Motif</th><th>Constantes</th><th>Médecin</th><th>Actions</th></tr></thead><tbody>${data.consultations.map(c=>`<tr><td>${fmt(c.date)}</td><td><b>${esc(c.patient)}</b></td><td>${esc(c.reason)}</td><td>${esc(c.temp||"—")} °C • ${esc(c.pulse||"—")} bpm</td><td>${esc(c.doctor)}</td><td><button class="btn secondary" onclick="editConsult('${c.id}')">Modifier</button> <button class="btn danger" onclick="deleteConsult('${c.id}')">Supprimer</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucune consultation.</div>'}</div>`}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`)}
function closeModal(){document.getElementById("modal")?.remove()}
function patientModal(existing=null){let p=existing||{};modal(existing?"Modifier le dossier patient":"Nouveau patient",`<form onsubmit="savePatient(event,'${p.id||""}')"><div class="form-grid"><div class="field"><label>Prénom</label><input name="first" value="${esc(p.first)}" required></div><div class="field"><label>Nom</label><input name="last" value="${esc(p.last)}" required></div><div class="field"><label>Date de naissance</label><input name="birth" type="date" value="${esc(p.birth)}" required></div><div class="field"><label>Téléphone</label><input name="phone" value="${esc(p.phone)}"></div><div class="field"><label>Groupe sanguin</label><select name="blood">${["Inconnu","A+","A-","B+","B-","AB+","AB-","O+","O-"].map(x=>`<option ${p.blood===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Allergies fictives</label><input name="allergies" value="${esc(p.allergies)}"></div><div class="field full"><label>Antécédents fictifs</label><textarea name="history">${esc(p.history)}</textarea></div><div class="field"><label>Vaccinations fictives</label><input name="vaccines" value="${esc(p.vaccines)}"></div><div class="field"><label>Traitements fictifs</label><input name="treatments" value="${esc(p.treatments)}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(p.notes)}</textarea></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)}
function savePatient(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),first:f.get("first"),last:f.get("last"),birth:f.get("birth"),phone:f.get("phone"),blood:f.get("blood"),allergies:f.get("allergies"),history:f.get("history"),vaccines:f.get("vaccines"),treatments:f.get("treatments"),notes:f.get("notes")};if(id){let i=data.patients.findIndex(p=>p.id===id);data.patients[i]=o}else data.patients.push(o);save();closeModal();render();toast(id?"Dossier modifié":"Patient ajouté")}
function openPatient(id){let p=data.patients.find(x=>x.id===id);modal("Dossier patient",`<div class="patient-head"><div class="big-avatar">${esc(p.first[0]+p.last[0])}</div><div><h2 style="margin:0">${esc(p.first)} ${esc(p.last)}</h2><div class="sub">Patient fictif • né(e) le ${fmt(p.birth)}</div></div></div><div class="tabs"><button class="active">Résumé</button><button onclick="showHistory('${p.id}')">Historique</button></div><div class="detail-grid"><div class="detail"><span>Téléphone</span>${esc(p.phone||"—")}</div><div class="detail"><span>Groupe sanguin</span>${esc(p.blood||"—")}</div><div class="detail"><span>Allergies</span>${esc(p.allergies||"—")}</div><div class="detail"><span>Antécédents</span>${esc(p.history||"—")}</div><div class="detail"><span>Vaccinations</span>${esc(p.vaccines||"—")}</div><div class="detail"><span>Traitements</span>${esc(p.treatments||"—")}</div></div><div class="section"><div class="card"><b>Notes</b><p class="sub">${esc(p.notes||"Aucune note.")}</p></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fermer</button><button class="btn secondary" onclick="closeModal();patientModal(data.patients.find(x=>x.id==='${p.id}'))">Modifier</button><button class="btn" onclick="closeModal();consultModal('${p.id}')">Nouvelle consultation</button><button class="btn danger" onclick="deletePatient('${p.id}')">Supprimer</button></div>`)}
function showHistory(id){let p=data.patients.find(x=>x.id===id),cs=data.consultations.filter(c=>c.patient===p.first+" "+p.last);document.querySelector(".tabs").insertAdjacentHTML("afterend",`<div class="timeline">${cs.length?cs.map(c=>`<div class="timeline-item"><b>${fmt(c.date)} — ${esc(c.reason)}</b><div class="sub">${esc(c.conclusion||c.notes||"Aucune conclusion.")}</div></div>`).join(""):"<div class='empty'>Aucune consultation.</div>"}</div>`)}
function deletePatient(id){if(confirm("Supprimer définitivement ce dossier fictif ?")){data.patients=data.patients.filter(p=>p.id!==id);save();closeModal();render();toast("Dossier supprimé")}}
function apptModal(existing=null){let a=existing||{};modal(existing?"Modifier le rendez-vous":"Nouveau rendez-vous",`<form onsubmit="saveAppt(event,'${a.id||""}')"><div class="form-grid"><div class="field full"><label>Patient</label><select name="patient">${data.patients.map(p=>`<option ${a.patient===p.first+" "+p.last?"selected":""}>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div><div class="field"><label>Date</label><input name="date" type="date" value="${esc(a.date||today())}" required></div><div class="field"><label>Heure</label><input name="time" type="time" value="${esc(a.time||"14:00")}" required></div><div class="field"><label>Médecin</label><select name="doctor">${USERS.map(u=>`<option ${a.doctor===u.name?"selected":""}>${u.name}</option>`).join("")}</select></div><div class="field"><label>Statut</label><select name="status">${["Prévu","Arrivé","En attente","En consultation","Terminé","Annulé"].map(s=>`<option ${a.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field full"><label>Motif</label><input name="reason" value="${esc(a.reason)}" required></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)}
function saveAppt(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),patient:f.get("patient"),date:f.get("date"),time:f.get("time"),doctor:f.get("doctor"),reason:f.get("reason"),status:f.get("status")};if(id)data.appointments[data.appointments.findIndex(a=>a.id===id)]=o;else data.appointments.push(o);save();closeModal();render();toast(id?"Rendez-vous modifié":"Rendez-vous ajouté")}
function editAppt(id){apptModal(data.appointments.find(a=>a.id===id))}
function deleteAppt(id){if(confirm("Supprimer définitivement ce rendez-vous fictif ?")){data.appointments=data.appointments.filter(a=>a.id!==id);save();render();toast("Rendez-vous supprimé")}}
function consultModal(pid="",existing=null){let c=existing||{},name=pid?(data.patients.find(p=>p.id===pid)?.first+" "+data.patients.find(p=>p.id===pid)?.last):c.patient||"";modal(existing?"Modifier la consultation":"Nouvelle consultation",`<form onsubmit="saveConsult(event,'${c.id||""}')"><div class="form-grid"><div class="field full"><label>Patient</label><select name="patient">${data.patients.map(p=>`<option ${name===p.first+" "+p.last?"selected":""}>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div><div class="field full"><label>Motif</label><input name="reason" value="${esc(c.reason)}" required></div><div class="field"><label>Température (°C)</label><input name="temp" value="${esc(c.temp)}" type="number" step=".1"></div><div class="field"><label>Pouls (bpm)</label><input name="pulse" value="${esc(c.pulse)}" type="number"></div><div class="field"><label>Tension</label><input name="bp" value="${esc(c.bp)}" placeholder="120/80"></div><div class="field"><label>Saturation (%)</label><input name="sat" value="${esc(c.sat)}" type="number"></div><div class="field full"><label>Symptômes / observations fictives</label><textarea name="notes">${esc(c.notes)}</textarea></div><div class="field full"><label>Examen clinique fictif</label><textarea name="exam">${esc(c.exam)}</textarea></div><div class="field full"><label>Diagnostic fictif</label><textarea name="diagnosis">${esc(c.diagnosis)}</textarea></div><div class="field full"><label>Traitement / prescription fictive</label><textarea name="treatment">${esc(c.treatment)}</textarea></div><div class="field full"><label>Conclusion</label><textarea name="conclusion">${esc(c.conclusion)}</textarea></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)}
function consultModalByName(name){let p=data.patients.find(x=>x.first+" "+x.last===name);consultModal(p?.id||"")}
function saveConsult(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),date:today(),patient:f.get("patient"),reason:f.get("reason"),temp:f.get("temp"),pulse:f.get("pulse"),bp:f.get("bp"),sat:f.get("sat"),notes:f.get("notes"),exam:f.get("exam"),diagnosis:f.get("diagnosis"),treatment:f.get("treatment"),conclusion:f.get("conclusion"),doctor:currentUser.name};if(id)data.consultations[data.consultations.findIndex(c=>c.id===id)]=o;else data.consultations.unshift(o);save();closeModal();render();toast(id?"Consultation modifiée":"Consultation enregistrée")}
function editConsult(id){consultModal("",data.consultations.find(c=>c.id===id))}
function deleteConsult(id){if(confirm("Supprimer définitivement cette consultation fictive ?")){data.consultations=data.consultations.filter(c=>c.id!==id);save();render();toast("Consultation supprimée")}}
render();