const USERS=[
{id:"raphael",name:"Raphaël",role:"Médecin",password:"2012"},
{id:"jade",name:"Jade",role:"Médecin",password:"2017"},
{id:"victoria",name:"Victoria",role:"Médecin",password:"2017"}
];
const KEY="cabinetMedicalProV3",SESSION="cabinetMedicalProSessionV3";
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const fmt=d=>d?new Date(d+"T12:00").toLocaleDateString("fr-FR"):"—";
const monthNames=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];
const FOOD_DB=[
['Eau','Boissons',0,250],['Eau gazeuse','Boissons',0,250],['Lait demi-écrémé','Produits laitiers',46,200],['Lait entier','Produits laitiers',61,200],['Lait végétal','Boissons',40,200],['Yaourt nature','Produits laitiers',61,125],['Yaourt aux fruits','Produits laitiers',100,125],['Fromage blanc','Produits laitiers',75,125],['Skyr','Produits laitiers',65,150],['Emmental','Produits laitiers',380,30],['Camembert','Produits laitiers',300,30],['Mozzarella','Produits laitiers',280,50],
['Pain blanc','Céréales',265,50],['Pain complet','Céréales',245,50],['Baguette','Céréales',275,60],['Pain de mie','Céréales',265,50],['Croissant','Céréales',406,50],['Pain au chocolat','Céréales',420,60],['Brioche','Céréales',330,50],['Céréales petit-déjeuner','Céréales',380,40],['Flocons d’avoine','Céréales',370,40],['Muesli','Céréales',390,45],['Riz blanc','Céréales',350,60],['Riz complet','Céréales',345,60],['Pâtes cuites','Céréales',150,150],['Spaghetti','Céréales',150,150],['Semoule cuite','Céréales',120,150],['Quinoa cuit','Céréales',120,150],['Boulgour cuit','Céréales',115,150],['Polenta','Céréales',80,150],['Pommes de terre','Céréales',80,150],['Patate douce','Céréales',86,150],
['Poulet rôti','Viandes/œufs/légumineuses',200,120],['Escalope de poulet','Viandes/œufs/légumineuses',165,120],['Dinde','Viandes/œufs/légumineuses',150,120],['Bœuf steak','Viandes/œufs/légumineuses',220,120],['Steak haché','Viandes/œufs/légumineuses',250,100],['Veau','Viandes/œufs/légumineuses',175,120],['Porc','Viandes/œufs/légumineuses',240,120],['Jambon blanc','Viandes/œufs/légumineuses',120,50],['Saucisse','Viandes/œufs/légumineuses',300,80],['Andouillette','Viandes/œufs/légumineuses',300,100],['Bacon','Viandes/œufs/légumineuses',500,30],['Saumon','Viandes/œufs/légumineuses',200,120],['Thon','Viandes/œufs/légumineuses',130,100],['Cabillaud','Viandes/œufs/légumineuses',85,120],['Sardines','Viandes/œufs/légumineuses',200,100],['Crevettes','Viandes/œufs/légumineuses',100,100],['Œuf','Viandes/œufs/légumineuses',143,60],['Omelette','Viandes/œufs/légumineuses',155,120],['Lentilles cuites','Viandes/œufs/légumineuses',115,150],['Pois chiches cuits','Viandes/œufs/légumineuses',165,150],['Haricots rouges','Viandes/œufs/légumineuses',125,150],['Tofu','Viandes/œufs/légumineuses',145,100],
['Carotte','Légumes',41,100],['Tomate','Légumes',18,120],['Salade verte','Légumes',15,80],['Courgette','Légumes',17,150],['Brocoli','Légumes',35,150],['Haricots verts','Légumes',31,150],['Concombre','Légumes',15,150],['Poivron','Légumes',31,120],['Épinards','Légumes',23,150],['Aubergine','Légumes',25,150],['Champignons','Légumes',22,150],['Chou-fleur','Légumes',25,150],['Poireau','Légumes',31,150],['Oignon','Légumes',40,80],['Ail','Légumes',149,10],['Artichaut','Légumes',47,120],['Asperges','Légumes',20,150],['Avocat','Légumes',160,80],['Betterave','Légumes',43,100],['Potiron','Légumes',26,150],
['Pomme','Fruits',52,150],['Banane','Fruits',89,120],['Orange','Fruits',47,150],['Clémentine','Fruits',47,100],['Fraise','Fruits',32,150],['Raisin','Fruits',69,120],['Poire','Fruits',57,150],['Pêche','Fruits',39,150],['Abricot','Fruits',48,120],['Kiwi','Fruits',61,100],['Ananas','Fruits',50,150],['Mangue','Fruits',60,150],['Pastèque','Fruits',30,200],['Melon','Fruits',34,200],['Framboise','Fruits',52,100],['Myrtille','Fruits',57,100],['Cerises','Fruits',63,100],['Prune','Fruits',46,100],['Abricot sec','Fruits',240,30],['Raisins secs','Fruits',300,30],['Compote de pomme','Fruits',70,100],
['Huile d’olive','Matières grasses',884,10],['Huile de colza','Matières grasses',884,10],['Beurre','Matières grasses',717,10],['Margarine','Matières grasses',720,10],['Mayonnaise','Matières grasses',680,15],['Crème fraîche','Matières grasses',300,20],['Noix','Matières grasses',650,30],['Amandes','Matières grasses',580,30],['Noisettes','Matières grasses',630,30],['Cacahuètes','Matières grasses',567,30],['Graines de chia','Matières grasses',486,15],
['Chocolat noir','Produits sucrés',550,30],['Chocolat au lait','Produits sucrés',535,30],['Biscuits','Produits sucrés',480,30],['Gâteau','Produits sucrés',350,80],['Tarte aux pommes','Produits sucrés',250,100],['Glace','Produits sucrés',210,100],['Bonbons','Produits sucrés',380,30],['Confiture','Produits sucrés',250,30],['Miel','Produits sucrés',304,20],['Nutella','Produits sucrés',539,30],['Soda','Produits sucrés',42,250],['Cola','Produits sucrés',42,330],['Jus d’orange','Boissons',45,200],['Jus de pomme','Boissons',46,200],['Café','Boissons',2,150],['Thé','Boissons',1,200],
['Pizza margherita','Plats composés',250,300],['Pizza quatre fromages','Plats composés',300,300],['Burger','Plats composés',250,250],['Cheeseburger','Plats composés',270,250],['Frites','Plats composés',310,150],['Kebab','Plats composés',220,350],['Sandwich jambon-fromage','Plats composés',250,200],['Lasagnes','Plats composés',160,300],['Couscous','Plats composés',150,350],['Paella','Plats composés',180,350],['Ratatouille','Plats composés',70,250],['Salade composée','Plats composés',100,250],['Soupe de légumes','Légumes',40,300],['Sushi','Plats composés',150,200],['Nems','Plats composés',220,100],['Tacos','Plats composés',250,300],['Pâtes carbonara','Plats composés',190,350],['Pâtes bolognaise','Plats composés',170,350],['Riz cantonais','Plats composés',170,300],['Curry de poulet','Plats composés',180,300],['Dahl de lentilles','Plats composés',130,300],['Chili con carne','Plats composés',150,300],['Quiche lorraine','Plats composés',300,150],['Crêpe','Plats composés',220,60],['Pancakes','Plats composés',225,100],['Gaufre','Plats composés',290,80],['Œufs brouillés','Plats composés',150,120]
];
const MEALS=[['breakfast','☀️ Petit-déjeuner'],['lunch','🍴 Déjeuner / brunch'],['snack','🍎 Goûter'],['dinner','🌙 Dîner / souper'],['extras','🍪 Grignotage']];
let foodDraft={};
function emptyFoodPlan(){return {breakfast:[],lunch:[],snack:[],dinner:[],extras:[]}}
const demo={
patients:[
{id:"p1",first:"Lucas",last:"Martin",birth:"2012-04-12",sex:"M",height:155,weight:48,phone:"06 00 00 00 00",blood:"O+",allergies:"Aucune connue",history:"Aucun antécédent fictif",vaccines:"À jour (simulation)",treatments:"Aucun",notes:"Patient de démonstration."},
{id:"p2",first:"Emma",last:"Bernard",birth:"2011-09-03",sex:"F",height:158,weight:49,phone:"06 11 11 11 11",blood:"A+",allergies:"Pollen",history:"Asthme fictif",vaccines:"À vérifier (simulation)",treatments:"Aucun",notes:"Dossier de démonstration."}
],
appointments:[
{id:"a1",date:today(),time:"09:00",patient:"Lucas Martin",reason:"Consultation de suivi",doctor:"Raphaël",status:"Prévu"},
{id:"a2",date:today(),time:"10:00",patient:"Emma Bernard",reason:"Contrôle",doctor:"Jade",status:"En attente"}
],
consultations:[],
prescriptions:[],
exams:[],
documents:[]
};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||demo;
let currentUser=null,page="dashboard",calendarDate=new Date();
function migrateNutritionData(){(data.consultations||[]).forEach(c=>{if(c.foodPlan)Object.values(c.foodPlan).flat().forEach(x=>{if(x.kcal==null){let f=FOOD_DB.find(z=>z[0]===x.name);if(f){x.cat=f[1];x.serving=f[3];x.kcal=Number(f[2])*Number(f[3])/100}else{x.kcal=0}}})});(data.patients||[]).forEach(p=>{if(!p.sex)p.sex="M"});save()}
migrateNutritionData();

function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function loginScreen(){
document.getElementById("app").innerHTML=`<div class="login"><div class="login-card"><div class="logo">✚</div><h1>Cabinet Médical Pro</h1><p class="sub">Version 5 — simulation de cabinet médical.</p><div class="notice">🔐 Connexion par utilisateur. Toutes les données de ce site sont fictives et restent dans ce navigateur.</div><b>Choisissez le médecin</b><div class="users">${USERS.map(u=>`<button class="user-btn" onclick="passwordModal('${u.id}')"><div class="avatar">${u.name[0]}</div><div><b>${u.name}</b><div class="sub">${u.role}</div></div></button>`).join("")}</div></div></div>`
}
function passwordModal(id){
let u=USERS.find(x=>x.id===id);
modal("Connexion — "+u.name,`<form onsubmit="doLogin(event,'${id}')"><div class="field"><label>Mot de passe</label><input id="loginPassword" type="password" inputmode="numeric" autocomplete="off" required autofocus placeholder="Mot de passe"></div><div id="loginError"></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Se connecter</button></div></form>`);
setTimeout(()=>document.getElementById("loginPassword")?.focus(),50)
}
function doLogin(e,id){
e.preventDefault();
let u=USERS.find(x=>x.id===id),p=document.getElementById("loginPassword").value;
if(p!==u.password){document.getElementById("loginError").innerHTML='<div class="error">Mot de passe incorrect.</div>';return}
localStorage.setItem(SESSION,id);closeModal();page="dashboard";render();toast("Connexion réussie")
}
function logout(){localStorage.removeItem(SESSION);render()}
function render(){
currentUser=USERS.find(u=>u.id===localStorage.getItem(SESSION));
if(!currentUser)return loginScreen();
document.getElementById("app").innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">✚ <span>Cabinet Médical Pro</span><small>V3 • SIMULATION FICTIVE</small></div><nav class="nav">
${nav("dashboard","⌂","Tableau de bord")}${nav("patients","👥","Patients")}${nav("appointments","▣","Rendez-vous")}${nav("calendar","📅","Calendrier")}${nav("waiting","⏱","Salle d’attente")}${nav("consultations","🩺","Consultations")}${nav("prescriptions","💊","Ordonnances")}${nav("exams","🧪","Examens")}${nav("documents","📎","Documents")}${nav("stats","📊","Statistiques")}${nav("admin","⚙️","Administration")}
</nav><button class="logout" onclick="logout()">↪ <span>Déconnexion</span></button></aside>
<main class="main"><header class="topbar"><div><h1>${titles[page]||"Cabinet"}</h1><div class="sub">Mode simulation médicale • données fictives</div></div><div class="profile"><div class="avatar">${currentUser.name[0]}</div><div><b>${esc(currentUser.name)}</b><div class="sub">${currentUser.role}</div></div></div></header><div id="content"></div></main></div>`;
pageRender()
}
const titles={dashboard:"Tableau de bord",patients:"Patients",appointments:"Rendez-vous",calendar:"Calendrier",waiting:"Salle d’attente",consultations:"Consultations",prescriptions:"Ordonnances",exams:"Examens",documents:"Documents",stats:"Statistiques",admin:"Administration"};
function nav(id,i,l){return `<button class="${page===id?"active":""}" onclick="go('${id}')">${i} <span>${l}</span></button>`}
function go(p){page=p;render()}
function pageRender(){
let c=document.getElementById("content");
c.innerHTML=page==="dashboard"?dashboard():page==="patients"?patients():page==="appointments"?appointments():page==="calendar"?calendar():page==="waiting"?waiting():page==="consultations"?consultations():page==="prescriptions"?prescriptions():page==="exams"?exams():page==="documents"?documents():page==="stats"?stats():admin()
}
function dashboard(){
let ap=data.appointments.filter(a=>a.date===today()),mine=ap.filter(a=>a.doctor===currentUser.name),waiting=ap.filter(a=>["Arrivé","En attente","En consultation"].includes(a.status));
return `<div class="grid">
<div class="card"><div class="stat-label">Patients</div><div class="stat-value">${data.patients.length}</div></div>
<div class="card"><div class="stat-label">Rendez-vous aujourd’hui</div><div class="stat-value">${ap.length}</div></div>
<div class="card"><div class="stat-label">Consultations</div><div class="stat-value">${data.consultations.length}</div></div>
<div class="card"><div class="stat-label">Salle d’attente</div><div class="stat-value">${waiting.length}</div></div>
</div>
<div class="section"><div class="section-head"><h2>Agenda du jour</h2><button class="btn" onclick="go('appointments')">Gérer l’agenda</button></div><div class="card table-wrap">${ap.length?apptTable(ap):'<div class="empty">Aucun rendez-vous aujourd’hui.</div>'}</div></div>
<div class="section"><div class="grid grid3">
<div class="card"><h3>Nouveau patient</h3><p class="sub">Créer un dossier fictif.</p><button class="btn" onclick="patientModal()">Créer</button></div>
<div class="card"><h3>Nouvelle consultation</h3><p class="sub">Ouvrir une consultation complète.</p><button class="btn" onclick="consultModal()">Ouvrir</button></div>
<div class="card"><h3>Ordonnance</h3><p class="sub">Créer une prescription fictive.</p><button class="btn" onclick="prescriptionModal()">Créer</button></div>
</div></div>`
}
function patients(){
return `<div class="section-head"><p class="sub">Dossiers médicaux fictifs.</p><div class="actions"><input id="search" class="search" placeholder="Rechercher..." oninput="filterPatients()"><button class="btn" onclick="patientModal()">+ Nouveau patient</button></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Naissance</th><th>Téléphone</th><th>Allergies</th><th></th></tr></thead><tbody id="rows">${patientRows(data.patients)}</tbody></table></div>`
}
function patientRows(a){return a.length?a.map(p=>`<tr><td><b>${esc(p.first)} ${esc(p.last)}</b></td><td>${fmt(p.birth)}</td><td>${esc(p.phone||"—")}</td><td>${esc(p.allergies||"—")}</td><td><button class="btn secondary" onclick="openPatient('${p.id}')">Dossier</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Aucun patient.</td></tr>`}
function filterPatients(){let q=document.getElementById("search").value.toLowerCase();document.getElementById("rows").innerHTML=patientRows(data.patients.filter(p=>(p.first+" "+p.last).toLowerCase().includes(q)))}
function appointments(){return `<div class="section-head"><p class="sub">Créer, modifier, supprimer et gérer les statuts.</p><button class="btn" onclick="apptModal()">+ Nouveau rendez-vous</button></div><div class="card table-wrap">${apptTable(data.appointments,true)}</div>`}
function apptTable(a,actions=false){
return `<table class="table"><thead><tr><th>Date</th><th>Heure</th><th>Patient</th><th>Motif</th><th>Médecin</th><th>Statut</th>${actions?"<th>Actions</th>":""}</tr></thead><tbody>
${[...a].sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).map(x=>`<tr><td>${fmt(x.date)}</td><td><b>${esc(x.time)}</b></td><td>${esc(x.patient)}</td><td>${esc(x.reason)}</td><td>${esc(x.doctor)}</td><td>${statusBadge(x.status)}</td>${actions?`<td><button class="btn secondary" onclick="editAppt('${x.id}')">Modifier</button> <button class="btn danger" onclick="deleteAppt('${x.id}')">Supprimer</button></td>`:""}</tr>`).join("")}</tbody></table>`
}
function statusBadge(s){return `<span class="badge ${s==="En attente"?"warning-b":s==="Terminé"?"success-b":s==="Annulé"?"danger-b":s==="En consultation"?"blue-b":""}">${esc(s||"Prévu")}</span>`}
function calendar(){
let y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;
let cells=[];for(let i=0;i<start;i++)cells.push(`<div class="day"></div>`);
for(let d=1;d<=last.getDate();d++){let date=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,events=data.appointments.filter(a=>a.date===date);cells.push(`<div class="day"><strong>${d}</strong>${events.map(e=>`<div class="event">${esc(e.time)} • ${esc(e.patient)}</div>`).join("")}</div>`)}
return `<div class="section-head"><div class="actions"><button class="btn secondary" onclick="changeMonth(-1)">‹</button><button class="btn secondary" onclick="calendarDate=new Date();render()">Aujourd’hui</button><button class="btn secondary" onclick="changeMonth(1)">›</button></div><h2>${monthNames[m]} ${y}</h2><button class="btn" onclick="apptModal()">+ Rendez-vous</button></div><div class="calendar">${["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(x=>`<div class="day" style="min-height:auto;background:#eef3f9"><strong>${x}</strong></div>`).join("")}${cells.join("")}</div>`
}
function changeMonth(n){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+n,1);render()}
function waiting(){
let a=data.appointments.filter(x=>x.date===today()&&x.status!=="Annulé");
return `<div class="section-head"><p class="sub">Patients arrivés au cabinet.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Heure</th><th>Patient</th><th>Motif</th><th>Statut</th><th>Actions</th></tr></thead><tbody>${a.length?a.map(x=>`<tr><td>${esc(x.time)}</td><td><b>${esc(x.patient)}</b></td><td>${esc(x.reason)}</td><td>${statusBadge(x.status)}</td><td><button class="btn secondary" onclick="setStatus('${x.id}','Arrivé')">Arrivé</button> <button class="btn" onclick="setStatus('${x.id}','En consultation');consultModalByName('${esc(x.patient)}')">Commencer</button> <button class="btn secondary" onclick="setStatus('${x.id}','Terminé')">Terminer</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Aucun patient dans la salle d’attente.</td></tr>`}</tbody></table></div>`
}
function setStatus(id,s){let a=data.appointments.find(x=>x.id===id);if(a){a.status=s;save();render();toast("Statut mis à jour")}}
function consultations(){
return `<div class="section-head"><p class="sub">Historique des consultations fictives.</p><button class="btn" onclick="consultModal()">+ Nouvelle consultation</button></div><div class="card table-wrap">${data.consultations.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Motif</th><th>Constantes</th><th>Médecin</th><th>Actions</th></tr></thead><tbody>${data.consultations.map(c=>`<tr><td>${fmt(c.date)}</td><td><b>${esc(c.patient)}</b></td><td>${esc(c.reason)}</td><td>${esc(c.temp||"—")} °C • ${esc(c.pulse||"—")} bpm</td><td>${esc(c.doctor)}</td><td class="actions"><button class="btn secondary" onclick="viewConsult('${c.id}')">Afficher</button><button class="btn secondary" onclick="editConsult('${c.id}')">Modifier</button><button class="btn danger" onclick="deleteConsult('${c.id}')">Supprimer</button><button class="btn" onclick="downloadConsult('${c.id}')">Télécharger</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucune consultation.</div>'}</div>`
}
function prescriptions(){
return `<div class="section-head"><p class="sub">Ordonnances entièrement fictives.</p><button class="btn" onclick="prescriptionModal()">+ Nouvelle ordonnance</button></div><div class="card table-wrap">${data.prescriptions.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Prescription</th><th>Médecin</th><th>Actions</th></tr></thead><tbody>${data.prescriptions.map(p=>`<tr><td>${fmt(p.date)}</td><td><b>${esc(p.patient)}</b></td><td>${esc(p.content).slice(0,100)}</td><td>${esc(p.doctor)}</td><td><button class="btn secondary" onclick="printPrescription('${p.id}')">Imprimer</button> <button class="btn danger" onclick="deletePrescription('${p.id}')">Supprimer</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucune ordonnance.</div>'}</div>`
}
function exams(){
return `<div class="section-head"><p class="sub">Examens et analyses fictifs.</p><button class="btn" onclick="examModal()">+ Ajouter un examen</button></div><div class="card table-wrap">${data.exams.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Type</th><th>Résultat</th><th>Médecin</th><th>Actions</th></tr></thead><tbody>${data.exams.map(x=>`<tr><td>${fmt(x.date)}</td><td>${esc(x.patient)}</td><td>${esc(x.type)}</td><td>${esc(x.result)}</td><td>${esc(x.doctor)}</td><td><button class="btn danger" onclick="deleteExam('${x.id}')">Supprimer</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucun examen.</div>'}</div>`
}
function documents(){
return `<div class="section-head"><p class="sub">Documents fictifs du cabinet.</p><button class="btn" onclick="documentModal()">+ Ajouter un document</button></div><div class="card table-wrap">${data.documents.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Document</th><th>Catégorie</th><th>Actions</th></tr></thead><tbody>${data.documents.map(d=>`<tr><td>${fmt(d.date)}</td><td>${esc(d.patient)}</td><td>${esc(d.name)}</td><td>${esc(d.category)}</td><td><button class="btn danger" onclick="deleteDocument('${d.id}')">Supprimer</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucun document.</div>'}</div>`
}
function stats(){
let total=data.appointments.length,done=data.appointments.filter(a=>a.status==="Terminé").length,cancel=data.appointments.filter(a=>a.status==="Annulé").length;
return `<div class="grid"><div class="card"><div class="stat-label">Patients</div><div class="stat-value">${data.patients.length}</div></div><div class="card"><div class="stat-label">Rendez-vous</div><div class="stat-value">${total}</div></div><div class="card"><div class="stat-label">Terminés</div><div class="stat-value">${done}</div></div><div class="card"><div class="stat-label">Annulés</div><div class="stat-value">${cancel}</div></div></div><div class="section"><div class="grid grid2"><div class="card"><h3>Activité du cabinet</h3><p>Consultations : <b>${data.consultations.length}</b></p><p>Ordonnances : <b>${data.prescriptions.length}</b></p><p>Examens : <b>${data.exams.length}</b></p><p>Documents : <b>${data.documents.length}</b></p></div><div class="card"><h3>Répartition des médecins</h3>${USERS.map(u=>`<p><b>${u.name}</b> — ${data.appointments.filter(a=>a.doctor===u.name).length} rendez-vous</p>`).join("")}</div></div></div>`
}
function admin(){
return `<div class="grid grid3"><div class="card"><h3>👨‍⚕️ Utilisateurs</h3>${USERS.map(u=>`<p><b>${u.name}</b><br><span class="sub">${u.role}</span></p>`).join("")}</div><div class="card"><h3>💾 Données locales</h3><p class="sub">Les données sont conservées uniquement dans ce navigateur.</p><button class="btn danger" onclick="resetData()">Réinitialiser les données fictives</button></div><div class="card"><h3>🔐 Sécurité</h3><p class="sub">Connexion par mot de passe pour le jeu. Ce système côté navigateur n'est pas une sécurité professionnelle.</p></div></div>`
}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`)}
function closeModal(){document.getElementById("modal")?.remove()}

function patientModal(existing=null){
let p=existing||{};
modal(existing?"Modifier le dossier patient":"Nouveau patient",`<form onsubmit="savePatient(event,'${p.id||""}')"><div class="form-grid">
<div class="field"><label>Prénom</label><input name="first" value="${esc(p.first)}" required></div><div class="field"><label>Nom</label><input name="last" value="${esc(p.last)}" required></div>
<div class="field"><label>Date de naissance</label><input name="birth" type="date" value="${esc(p.birth)}" required></div><div class="field"><label>Sexe (pour la simulation)</label><select name="sex"><option value="F" ${p.sex==="F"?"selected":""}>Féminin</option><option value="M" ${p.sex==="M"?"selected":""}>Masculin</option></select></div>
<div class="field"><label>Taille (cm)</label><input name="height" type="number" min="50" max="250" step="1" value="${esc(p.height)}"></div><div class="field"><label>Poids (kg)</label><input name="weight" type="number" min="2" max="300" step="0.1" value="${esc(p.weight)}"></div>
<div class="field"><label>Téléphone</label><input name="phone" value="${esc(p.phone)}"></div><div class="field"><label>Groupe sanguin</label><select name="blood">${["Inconnu","A+","A-","B+","B-","AB+","AB-","O+","O-"].map(x=>`<option ${p.blood===x?"selected":""}>${x}</option>`).join("")}</select></div>
<div class="field"><label>Allergies fictives</label><input name="allergies" value="${esc(p.allergies)}"></div><div class="field"><label>Vaccinations fictives</label><input name="vaccines" value="${esc(p.vaccines)}"></div>
<div class="field full"><label>Antécédents fictifs</label><textarea name="history">${esc(p.history)}</textarea></div><div class="field"><label>Traitements fictifs</label><input name="treatments" value="${esc(p.treatments)}"></div><div class="field"><label>Notes</label><textarea name="notes">${esc(p.notes)}</textarea></div></div>
<div class="notice">Les données de taille/poids/sexe servent uniquement à une estimation pédagogique des besoins énergétiques dans le jeu.</div>
<div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)
}
function savePatient(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),first:f.get("first"),last:f.get("last"),birth:f.get("birth"),sex:f.get("sex"),height:f.get("height"),weight:f.get("weight"),phone:f.get("phone"),blood:f.get("blood"),allergies:f.get("allergies"),history:f.get("history"),vaccines:f.get("vaccines"),treatments:f.get("treatments"),notes:f.get("notes")};if(id)data.patients[data.patients.findIndex(p=>p.id===id)]=o;else data.patients.push(o);save();closeModal();render();toast(id?"Dossier modifié":"Patient ajouté")}
function openPatient(id){
let p=data.patients.find(x=>x.id===id);
modal("Dossier patient",`<div class="patient-head"><div class="big-avatar">${esc(p.first[0]+p.last[0])}</div><div><h2 style="margin:0">${esc(p.first)} ${esc(p.last)}</h2><div class="sub">Patient fictif • né(e) le ${fmt(p.birth)}</div></div></div>
<div class="detail-grid"><div class="detail"><span>Âge</span>${ageFromBirth(p.birth)} ans</div><div class="detail"><span>Sexe</span>${p.sex==="F"?"Féminin":p.sex==="M"?"Masculin":"—"}</div><div class="detail"><span>Taille / poids</span>${esc(p.height||"—")} cm • ${esc(p.weight||"—")} kg</div><div class="detail"><span>Téléphone</span>${esc(p.phone||"—")}</div><div class="detail"><span>Groupe sanguin</span>${esc(p.blood||"—")}</div><div class="detail"><span>Allergies</span>${esc(p.allergies||"—")}</div><div class="detail"><span>Antécédents</span>${esc(p.history||"—")}</div><div class="detail"><span>Vaccinations</span>${esc(p.vaccines||"—")}</div><div class="detail"><span>Traitements</span>${esc(p.treatments||"—")}</div></div>
<div class="section"><div class="card"><b>Notes</b><p class="sub">${esc(p.notes||"Aucune note.")}</p></div></div>
<div class="section"><h3>Historique des consultations</h3><div class="timeline">${data.consultations.filter(c=>c.patient===p.first+" "+p.last).length?data.consultations.filter(c=>c.patient===p.first+" "+p.last).map(c=>`<div class="timeline-item"><b>${fmt(c.date)} — ${esc(c.reason)}</b><div class="sub">${esc(c.conclusion||c.notes||"Aucune conclusion.")}</div></div>`).join(""):"<div class='empty'>Aucune consultation.</div>"}</div></div>
<div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fermer</button><button class="btn secondary" onclick="closeModal();patientModal(data.patients.find(x=>x.id==='${p.id}'))">Modifier</button><button class="btn" onclick="closeModal();consultModal('${p.id}')">Nouvelle consultation</button><button class="btn danger" onclick="deletePatient('${p.id}')">Supprimer</button></div>`)
}
function deletePatient(id){if(confirm("Supprimer définitivement ce dossier fictif ?")){data.patients=data.patients.filter(p=>p.id!==id);save();closeModal();render();toast("Dossier supprimé")}}

function apptModal(existing=null){
let a=existing||{};
modal(existing?"Modifier le rendez-vous":"Nouveau rendez-vous",`<form onsubmit="saveAppt(event,'${a.id||""}')"><div class="form-grid">
<div class="field full"><label>Patient</label><select name="patient">${data.patients.map(p=>`<option ${a.patient===p.first+" "+p.last?"selected":""}>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div>
<div class="field"><label>Date</label><input name="date" type="date" value="${esc(a.date||today())}" required></div><div class="field"><label>Heure</label><input name="time" type="time" value="${esc(a.time||"14:00")}" required></div>
<div class="field"><label>Médecin</label><select name="doctor">${USERS.map(u=>`<option ${a.doctor===u.name?"selected":""}>${u.name}</option>`).join("")}</select></div>
<div class="field"><label>Statut</label><select name="status">${["Prévu","Arrivé","En attente","En consultation","Terminé","Annulé"].map(s=>`<option ${a.status===s?"selected":""}>${s}</option>`).join("")}</select></div>
<div class="field full"><label>Motif</label><input name="reason" value="${esc(a.reason)}" required></div></div>
<div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)
}
function saveAppt(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),patient:f.get("patient"),date:f.get("date"),time:f.get("time"),doctor:f.get("doctor"),reason:f.get("reason"),status:f.get("status")};if(id)data.appointments[data.appointments.findIndex(a=>a.id===id)]=o;else data.appointments.push(o);save();closeModal();render();toast(id?"Rendez-vous modifié":"Rendez-vous ajouté")}
function editAppt(id){apptModal(data.appointments.find(a=>a.id===id))}
function deleteAppt(id){if(confirm("Supprimer définitivement ce rendez-vous fictif ?")){data.appointments=data.appointments.filter(a=>a.id!==id);save();render();toast("Rendez-vous supprimé")}}

function ageFromBirth(b){if(!b)return 0;let d=new Date(b+"T12:00"),n=new Date(),a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return Math.max(0,a)}
const ACTIVITY=[
{id:'null',label:'Activité physique presque nulle',desc:'La personne reste au lit et ne se lève que pour manger',factor:1.20},
{id:'low',label:'Activité physique faible',desc:"Pas de sport, pas d'efforts physiques significatifs",factor:1.35},
{id:'medium',label:'Activité physique moyenne',desc:'Activité sportive au moins une fois par semaine, efforts modérés',factor:1.55},
{id:'high',label:'Activité physique importante',desc:'Activité sportive régulière et intense ou efforts physiques importants',factor:1.725},
{id:'veryhigh',label:'Activité physique très importante',desc:'Sportif de haut niveau ou entraînement intensif',factor:1.90}
];
function getPatient(name){return data.patients.find(p=>p.first+" "+p.last===name)}
function estimateNeeds(patient,activityId){if(!patient||!patient.weight)return null;let age=ageFromBirth(patient.birth),w=Number(patient.weight),h=Number(patient.height)||170,sex=patient.sex||'M',bmr;if(age>=18){bmr=sex==='F'?447.593+9.247*w+3.098*h-4.33*age:88.362+13.397*w+4.799*h-5.677*age}else if(age>=10){bmr=sex==='F'?13.384*w+692.6:17.686*w+658.2}else{bmr=22*w+500}let a=ACTIVITY.find(x=>x.id===activityId)||ACTIVITY[2],needs=Math.round(bmr*a.factor);return {age,bmr:Math.round(bmr),factor:a.factor,needs,activity:a.label}}
function nutritionTotals(plan){let kcal=0;Object.values(plan||{}).flat().forEach(x=>kcal+=Number(x.kcal||0)*Number(x.qty||1));return Math.round(kcal)}
function foodCounts(plan){let counts={};(plan?Object.values(plan):[]).flat().forEach(x=>{counts[x.cat]=(counts[x.cat]||0)+Number(x.qty||1)});return counts}
function foodPlanLabel(plan){return plan&&Object.values(plan).some(a=>a?.length)?'Bilan alimentaire créé':'Aucun bilan alimentaire'}
function consultModal(pid="",existing=null){
let c=existing||{},name=pid?(data.patients.find(p=>p.id===pid)?.first+" "+data.patients.find(p=>p.id===pid)?.last):c.patient||"";
foodDraft=JSON.parse(JSON.stringify(c.foodPlan||emptyFoodPlan()));
let act=c.activityId||'medium',patient=getPatient(name),est=estimateNeeds(patient,act);
modal(existing?"Modifier la consultation":"Nouvelle consultation",`<form onsubmit="saveConsult(event,'${c.id||""}')"><div class="form-grid">
<div class="field full"><label>Patient</label><select name="patient" onchange="refreshNutritionPreview(this.value)">${data.patients.map(p=>`<option ${name===p.first+" "+p.last?"selected":""}>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div>
<div class="field full"><label>Motif</label><input name="reason" value="${esc(c.reason)}" required></div>
<div class="field"><label>Température (°C)</label><input name="temp" value="${esc(c.temp)}" type="number" step=".1"></div><div class="field"><label>Pouls (bpm)</label><input name="pulse" value="${esc(c.pulse)}" type="number"></div>
<div class="field"><label>Tension</label><input name="bp" value="${esc(c.bp)}" placeholder="120/80"></div><div class="field"><label>Saturation (%)</label><input name="sat" value="${esc(c.sat)}" type="number"></div>
<div class="field full"><label>Symptômes / observations fictives</label><textarea name="notes">${esc(c.notes)}</textarea></div><div class="field full"><label>Examen clinique fictif</label><textarea name="exam">${esc(c.exam)}</textarea></div><div class="field full"><label>Diagnostic fictif</label><textarea name="diagnosis">${esc(c.diagnosis)}</textarea></div><div class="field full"><label>Traitement / prescription fictive</label><textarea name="treatment">${esc(c.treatment)}</textarea></div><div class="field full"><label>Conclusion</label><textarea name="conclusion">${esc(c.conclusion)}</textarea></div>
<div class="field full"><div class="card nutrition-card"><div class="section-head"><div><b>🥗 Bilan alimentaire de la journée</b><div class="sub">Saisie inspirée de la présentation de référence.</div></div><button type="button" class="btn" onclick="openFoodPlanner()">${foodPlanLabel(foodDraft)==='Bilan alimentaire créé'?'Modifier la saisie':'Créer le bilan'}</button></div><div id="foodSummary">${foodPlanSummary(foodDraft)}</div></div></div>
<div class="field full"><div class="card activity-card"><h3 style="margin-top:0">🏃 Dépenses liées à l'activité physique</h3><p class="sub">Sélectionner le cas correspondant au sujet :</p>${ACTIVITY.map(a=>`<label class="activity-option"><input type="radio" name="activity" value="${a.id}" ${act===a.id?'checked':''} onchange="refreshNutritionPreview(document.querySelector('[name=patient]').value)"><span><b>${a.label}</b><small>${a.desc}</small></span></label>`).join('')}<div id="energyPreview">${energyPreview(patient,act)}</div></div></div>
</div><div class="notice">⚠️ Simulation de jeu : les besoins et apports énergétiques sont des estimations pédagogiques, pas des recommandations médicales.</div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)
}
function energyPreview(patient,act){let est=estimateNeeds(patient,act),k=nutritionTotals(foodDraft);if(!est)return '<div class="notice">Renseigne au minimum le poids du patient (et idéalement taille, date de naissance et sexe) dans son dossier pour afficher une estimation.</div>';let pct=est.needs?Math.round(k/est.needs*100):0;return `<div class="energy-box"><div><b>Apports saisis :</b> ${k.toLocaleString('fr-FR')} kcal</div><div><b>Besoins estimés :</b> ${est.needs.toLocaleString('fr-FR')} kcal/jour</div><div class="energy-bar"><span style="width:${Math.min(100,pct)}%"></span></div><b>${pct}% des besoins estimés</b></div>`}
function refreshNutritionPreview(name){let act=document.querySelector('input[name=activity]:checked')?.value||'medium',el=document.getElementById('energyPreview');if(el)el.innerHTML=energyPreview(getPatient(name),act)}
function foodPlanSummary(plan){let counts=foodCounts(plan);if(!plan||!Object.values(plan).some(a=>a?.length))return '<span class="sub">Aucun repas saisi.</span>';return `<b>${Object.values(plan).flat().length} aliments/plats saisis</b> • ${Object.entries(counts).map(([k,v])=>`${esc(k)} : ${v}`).join(' • ')}`}
let foodSearchMeal='breakfast',foodSearchTimer=null,onlineResults=[];
function openFoodPlanner(){
foodSearchMeal=MEALS[0][0];
let mealTabs=MEALS.map(([k,l])=>`<label class="meal-radio"><input type="radio" name="mealChoice" value="${k}" ${k===foodSearchMeal?'checked':''} onchange="foodSearchMeal=this.value;renderFoodPlanner()"><span>${l}</span></label>`).join('');
document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="foodModal"><div class="modal food-modal"><div class="modal-head"><div><h2>🥗 Saisie des aliments consommés au cours d'une journée</h2><div class="sub">Choisissez le repas, recherchez un aliment puis cliquez dessus pour l'ajouter.</div></div><button class="close" onclick="closeFoodPlanner()">×</button></div><div class="meal-tabs">${mealTabs}</div><div id="foodPlannerBody"></div><div class="modal-actions"><button class="btn secondary" onclick="closeFoodPlanner()">Annuler</button><button class="btn" onclick="saveFoodPlanner()">Saisie terminée</button></div></div></div>`);renderFoodPlanner()}
function renderFoodPlanner(){let modalEl=document.getElementById('foodModal');if(!modalEl)return;let meal=foodSearchMeal,arr=foodDraft[meal]||[],query=(document.getElementById('foodSearch')?.value||'').trim().toLowerCase(),local=FOOD_DB.filter(f=>!query||f[0].toLowerCase().includes(query)).slice(0,80);document.getElementById('foodPlannerBody').innerHTML=`<div class="food-layout"><div class="food-left"><div class="food-box"><h3>Recherche d'un aliment par son nom :</h3><p class="sub">Tapez quelques lettres du nom de l'aliment.</p><input id="foodSearch" class="food-search" value="${esc(query)}" oninput="filterFoodResults()" placeholder="Rechercher : pomme, riz, pizza..."><h3>Aliments correspondant à la recherche :</h3><div id="foodResults" class="food-results">${foodResultsHTML(local)}</div><button class="btn secondary" style="margin-top:10px" onclick="customFoodModal()">+ Créer un aliment / plat personnalisé</button><button class="btn secondary" style="margin-top:10px" onclick="searchOnlineFoods()">🌍 Recherche mondiale</button></div></div><div class="food-right"><div class="food-box"><h3>Repas saisi : ${esc(MEALS.find(x=>x[0]===meal)?.[1]||'')}</h3><p class="sub">Cliquez sur une ligne pour la supprimer.</p><div id="selectedFoods">${selectedFoodsHTML(meal)}</div></div><div class="energy-live">${energyLiveHTML()}</div></div></div>`}
function foodResultsHTML(list){return list.map((f,i)=>`<button class="food-result" onclick="addFood('${foodSearchMeal}',${i},'${encodeURIComponent(f[0])}')"><b>${esc(f[0])}</b><span>${esc(f[1])} • ${f[3]||100} g • ${f[2]||0} kcal/100g</span></button>`).join('')||'<div class="empty">Aucun résultat.</div>'}
function filterFoodResults(){let q=(document.getElementById('foodSearch')?.value||'').toLowerCase();let list=FOOD_DB.filter(f=>!q||f[0].toLowerCase().includes(q)).slice(0,80);document.getElementById('foodResults').innerHTML=foodResultsHTML(list)}
function addFood(key,idx,encoded){let name=decodeURIComponent(encoded),f=FOOD_DB.find(x=>x[0]===name);if(!f)return;foodDraft[key].push({name:f[0],cat:f[1],kcal:Number(f[2]||0)*Number(f[3]||100)/100,serving:f[3]||100,qty:1});renderFoodPlanner()}
function selectedFoodsHTML(key){let arr=foodDraft[key]||[];if(!arr.length)return '<div class="empty">Aucun aliment saisi pour ce repas.</div>';return arr.map((x,i)=>`<button class="selected-food" onclick="removeFood('${key}',${i})"><span><b>${esc(x.name)}</b><small>${esc(x.cat)} • ${Math.round(x.kcal*x.qty)} kcal • ${x.serving||100} g/portion × ${x.qty||1}</small></span><b>×</b></button>`).join('')}
function removeFood(key,i){foodDraft[key].splice(i,1);renderFoodPlanner()}
function energyLiveHTML(){let k=nutritionTotals(foodDraft),cats=foodCounts(foodDraft);return `<div><b>Apports :</b> ${k.toLocaleString('fr-FR')} kcal</div><div class="cat-pills">${Object.entries(cats).map(([c,v])=>`<span>${esc(c)} : ${v}</span>`).join('')}</div>`}
function saveFoodPlanner(){closeFoodPlanner();let x=document.getElementById('foodSummary');if(x)x.innerHTML=foodPlanSummary(foodDraft);let el=document.getElementById('energyPreview');if(el){let name=document.querySelector('[name=patient]')?.value,act=document.querySelector('input[name=activity]:checked')?.value||'medium';el.innerHTML=energyPreview(getPatient(name),act)}toast('Saisie alimentaire enregistrée')}
function closeFoodPlanner(){document.getElementById('foodModal')?.remove()}
async function searchOnlineFoods(){let q=(document.getElementById('foodSearch')?.value||'').trim();if(!q){toast('Saisis un aliment à rechercher');return}let box=document.getElementById('foodResults');box.innerHTML='<div class="empty">Recherche mondiale en cours…</div>';try{let url='https://world.openfoodfacts.org/api/v2/search?search_terms='+encodeURIComponent(q)+'&page_size=30&fields=product_name,generic_name,categories_tags,nutriments,serving_size';let r=await fetch(url);let j=await r.json();onlineResults=(j.products||[]).filter(x=>x.product_name).map(x=>{let n=x.nutriments||{},cat=mapOffCategory((x.categories_tags||[]).join(' '));return {name:x.product_name,cat,kcal:Number(n['energy-kcal_100g']||0),serving:parseServing(x.serving_size)||100}});box.innerHTML=onlineResults.length?onlineResults.map((f,i)=>`<button class="food-result" onclick="addOnlineFood(${i})"><b>${esc(f.name)}</b><span>${esc(f.cat)} • ${f.serving} g • ${f.kcal||0} kcal/100g</span></button>`).join(''):'<div class="empty">Aucun produit trouvé.</div>'}catch(e){console.error(e);box.innerHTML='<div class="empty">La recherche mondiale est indisponible. La base locale reste disponible.</div>'}}
function parseServing(s){let m=String(s||'').replace(',','.').match(/(\d+(?:\.\d+)?)\s*g/i);return m?Number(m[1]):null}
function mapOffCategory(c){c=c.toLowerCase();if(/beverage|boisson|drink|water/.test(c))return'Boissons';if(/fruit/.test(c))return'Fruits';if(/vegetable|legume|salad/.test(c))return'Légumes';if(/dairy|milk|cheese|yogurt/.test(c))return'Produits laitiers';if(/meat|fish|egg|seafood|legume/.test(c))return'Viandes/œufs/légumineuses';if(/cereal|bread|pasta|rice|grain/.test(c))return'Céréales';if(/sweet|chocolate|dessert|candy|cake|biscuit/.test(c))return'Produits sucrés';if(/oil|fat|butter|nuts/.test(c))return'Matières grasses';return'Plats composés'}
function addOnlineFood(i){let f=onlineResults[i];if(!f)return;foodDraft[foodSearchMeal].push({name:f.name,cat:f.cat,kcal:(f.kcal||0)*f.serving/100,serving:f.serving||100,qty:1});renderFoodPlanner();toast('Produit ajouté')}
function customFoodModal(){modal('Créer un aliment ou un plat',`<form onsubmit="saveCustomFood(event)"><div class="form-grid"><div class="field full"><label>Nom</label><input name="name" required placeholder="Ex. couscous maison"></div><div class="field"><label>Catégorie</label><select name="cat">${['Boissons','Céréales','Légumes','Fruits','Produits laitiers','Viandes/œufs/légumineuses','Matières grasses','Produits sucrés','Plats composés'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Énergie (kcal / 100 g)</label><input name="kcal" type="number" step="1" min="0" required></div><div class="field"><label>Poids d'une portion (g)</label><input name="serving" type="number" step="1" min="1" value="100" required></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Ajouter</button></div></form>`)}
function saveCustomFood(e){e.preventDefault();let f=new FormData(e.target),item={name:f.get('name'),cat:f.get('cat'),kcal:Number(f.get('kcal'))*Number(f.get('serving'))/100,serving:Number(f.get('serving')),qty:1};foodDraft[foodSearchMeal].push(item);closeModal();renderFoodPlanner();toast('Aliment/plat personnalisé ajouté')}
function pyramidHTML(plan){let counts=foodCounts(plan),cats=['Boissons','Céréales','Légumes','Fruits','Produits laitiers','Viandes/œufs/légumineuses','Matières grasses','Produits sucrés'];let max=Math.max(1,...cats.map(c=>counts[c]||0));return `<div class="pyramid-wrap"><div class="pyramid-title">Pyramide personnalisée</div><div class="pyramid">${cats.map((c,i)=>{let n=counts[c]||0,w=22+i*9;let intensity=n?Math.min(.95,.35+.6*n/max):.18;return `<div class="pyr-level" style="width:${w}%;opacity:${intensity}"><span>${esc(c)}</span><b>${n} portion${n>1?'s':''}</b></div>`}).reverse().join('')}</div><div class="pyramid-legend">La hauteur/présence des catégories reflète uniquement la saisie de la journée. Visualisation ludique, pas une recommandation.</div></div>`}
function nutritionStatsHTML(plan,patient,activity){let k=nutritionTotals(plan),est=estimateNeeds(patient,activity),counts=foodCounts(plan);return `<div class="nutrition-stats"><div class="stat"><span>Apports</span><b>${k.toLocaleString('fr-FR')} kcal</b></div><div class="stat"><span>Besoins estimés</span><b>${est?est.needs.toLocaleString('fr-FR')+' kcal/j':'—'}</b></div><div class="stat"><span>Ratio</span><b>${est?Math.round(k/est.needs*100)+'%':'—'}</b></div></div><div class="section"><h3>Statistiques par catégorie</h3><div class="cat-stats">${['Boissons','Céréales','Légumes','Fruits','Produits laitiers','Viandes/œufs/légumineuses','Matières grasses','Produits sucrés'].map(c=>`<div><span>${esc(c)}</span><div class="mini-bar"><i style="width:${Math.min(100,(counts[c]||0)*20)}%"></i></div><b>${counts[c]||0}</b></div>`).join('')}</div></div>`}
function viewConsult(id){let c=data.consultations.find(x=>x.id===id);if(!c){toast('Consultation introuvable');return}let plan={...emptyFoodPlan(),...(c.foodPlan||{})};let patient=getPatient(c.patient),activity=c.activityId||'medium';modal('Consultation — affichage',`<div class="patient-head"><div class="big-avatar">${esc(c.patient.split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><h2 style="margin:0">${esc(c.patient)}</h2><div class="sub">${fmt(c.date)} • ${esc(c.doctor)} • ${esc(c.reason)}</div></div></div><div class="detail-grid"><div class="detail"><span>Température</span>${esc(c.temp||'—')} °C</div><div class="detail"><span>Pouls</span>${esc(c.pulse||'—')} bpm</div><div class="detail"><span>Tension</span>${esc(c.bp||'—')}</div><div class="detail"><span>Saturation</span>${esc(c.sat||'—')} %</div></div><div class="section"><div class="card"><b>Symptômes / observations</b><p>${esc(c.notes||'—')}</p><b>Examen clinique</b><p>${esc(c.exam||'—')}</p><b>Diagnostic fictif</b><p>${esc(c.diagnosis||'—')}</p><b>Traitement / prescription fictive</b><p>${esc(c.treatment||'—')}</p><b>Conclusion</b><p>${esc(c.conclusion||'—')}</p></div></div><div class="section"><div class="card"><h2>🏃 Activité physique</h2><p><b>${esc((ACTIVITY.find(a=>a.id===activity)||ACTIVITY[2]).label)}</b></p><p class="sub">${esc((ACTIVITY.find(a=>a.id===activity)||ACTIVITY[2]).desc)}</p></div></div><div class="section"><div class="section-head"><h2>🥗 Pyramide alimentaire personnalisée</h2><span class="badge">${foodPlanLabel(plan)}</span></div>${Object.values(plan).some(a=>a.length)?pyramidHTML(plan):'<div class="empty">Aucun bilan alimentaire n’a été créé.</div>'}${nutritionStatsHTML(plan,patient,activity)}</div><div class="section"><h3>Journée alimentaire</h3>${mealSummary(plan)}</div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fermer</button><button class="btn secondary" onclick="closeModal();editConsult('${c.id}')">Modifier</button><button class="btn" onclick="downloadConsult('${c.id}')">Télécharger</button></div>`)}
function mealSummary(plan){return MEALS.map(([k,l])=>`<div class="card" style="margin-bottom:8px"><b>${l}</b><div class="sub">${(plan[k]||[]).length?plan[k].map(x=>`${esc(x.name)} × ${x.qty||1} (${Math.round(Number(x.kcal||0)*Number(x.qty||1))} kcal)`).join(' • '):'Aucun aliment saisi.'}</div></div>`).join('')}
function downloadConsult(id){let c=data.consultations.find(x=>x.id===id);if(!c){toast('Consultation introuvable');return}let plan={...emptyFoodPlan(),...(c.foodPlan||{})},patient=getPatient(c.patient),activity=c.activityId||'medium',est=estimateNeeds(patient,activity),k=nutritionTotals(plan);let cats=foodCounts(plan);let pyramid=cats?['Boissons','Céréales','Légumes','Fruits','Produits laitiers','Viandes/œufs/légumineuses','Matières grasses','Produits sucrés'].map((x,i)=>`<div class="pyr" style="width:${20+i*10}%;opacity:${Math.min(.95,.35+.6*(cats[x]||0)/Math.max(1,...Object.values(cats)))}">${esc(x)} — ${cats[x]||0} portions</div>`).reverse().join(''):'';let meals=mealSummaryText(plan);let html=`<!doctype html><html lang="fr"><meta charset="utf-8"><title>Consultation fictive - ${esc(c.patient)}</title><style>body{font-family:Arial;padding:40px;color:#172033;max-width:1000px;margin:auto}h1{color:#1769e0}.box{border:1px solid #d9e2ef;border-radius:14px;padding:18px;margin:16px 0}.pyramid{display:flex;flex-direction:column;align-items:center;gap:4px}.pyr{padding:9px;background:#e7f0ff;text-align:center;border-radius:5px}.bar{height:18px;background:#e8edf4;border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:#1769e0}.muted{color:#68778b}</style><h1>Cabinet Médical Pro</h1><p><b>CONSULTATION — SIMULATION FICTIVE</b></p><div class="box"><b>Patient :</b> ${esc(c.patient)}<br><b>Date :</b> ${fmt(c.date)}<br><b>Médecin :</b> ${esc(c.doctor)}<br><b>Motif :</b> ${esc(c.reason)}</div><div class="box"><b>Constantes</b><p>Température : ${esc(c.temp||'—')} °C • Pouls : ${esc(c.pulse||'—')} bpm • Tension : ${esc(c.bp||'—')} • Saturation : ${esc(c.sat||'—')} %</p></div><div class="box"><b>Observations</b><p>${esc(c.notes||'—')}</p><b>Examen</b><p>${esc(c.exam||'—')}</p><b>Diagnostic fictif</b><p>${esc(c.diagnosis||'—')}</p><b>Traitement fictif</b><p>${esc(c.treatment||'—')}</p><b>Conclusion</b><p>${esc(c.conclusion||'—')}</p></div><div class="box"><h2>🥗 Alimentation</h2><p>Apports saisis : <b>${k.toLocaleString('fr-FR')} kcal</b></p><p>Besoins estimés : <b>${est?est.needs.toLocaleString('fr-FR')+' kcal/j':'non calculables'}</b></p><p>Activité : <b>${esc((ACTIVITY.find(a=>a.id===activity)||ACTIVITY[2]).label)}</b></p><div class="pyramid">${pyramid}</div><h3>Journée</h3>${meals}</div><p class="muted">Document de jeu uniquement. Estimations nutritionnelles pédagogiques sans valeur médicale.</p></html>`;let blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='consultation-'+c.patient.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('Consultation téléchargée')}
function mealSummaryText(plan){return MEALS.map(([k,l])=>`<p><b>${l}</b><br>${(plan[k]||[]).length?plan[k].map(x=>`${esc(x.name)} × ${x.qty||1} — ${Math.round(Number(x.kcal||0)*Number(x.qty||1))} kcal`).join('<br>'):'Aucun aliment saisi.'}</p>`).join('')}
function consultModalByName(name){let p=data.patients.find(x=>x.first+" "+x.last===name);consultModal(p?.id||"")}
function saveConsult(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),date:today(),patient:f.get('patient'),reason:f.get('reason'),temp:f.get('temp'),pulse:f.get('pulse'),bp:f.get('bp'),sat:f.get('sat'),notes:f.get('notes'),exam:f.get('exam'),diagnosis:f.get('diagnosis'),treatment:f.get('treatment'),conclusion:f.get('conclusion'),doctor:currentUser.name,activityId:f.get('activity')||'medium',foodPlan:JSON.parse(JSON.stringify(foodDraft))};if(id)data.consultations[data.consultations.findIndex(c=>c.id===id)]=o;else data.consultations.unshift(o);save();closeModal();render();toast(id?'Consultation modifiée':'Consultation enregistrée')}
function editConsult(id){consultModal('',data.consultations.find(c=>c.id===id))}
function deleteConsult(id){if(confirm("Supprimer définitivement cette consultation fictive ?")){data.consultations=data.consultations.filter(c=>c.id!==id);save();render();toast("Consultation supprimée")}}

function prescriptionModal(existing=null){
let p=existing||{};
modal("Nouvelle ordonnance fictive",`<form onsubmit="savePrescription(event,'${p.id||""}')"><div class="form-grid">
<div class="field full"><label>Patient</label><select name="patient">${data.patients.map(x=>`<option ${p.patient===x.first+" "+x.last?"selected":""}>${esc(x.first+" "+x.last)}</option>`).join("")}</select></div>
<div class="field"><label>Date</label><input type="date" name="date" value="${p.date||today()}" required></div>
<div class="field"><label>Durée fictive</label><input name="duration" value="${esc(p.duration||"7 jours")}"></div>
<div class="field full"><label>Prescription fictive</label><textarea name="content" placeholder="Exemple de médicament fictif, posologie, fréquence...">${esc(p.content)}</textarea></div></div>
<div class="notice">⚠️ Cette ordonnance est uniquement un accessoire de jeu et n'a aucune valeur médicale.</div>
<div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)
}
function savePrescription(e,id){e.preventDefault();let f=new FormData(e.target),o={id:id||uid(),date:f.get("date"),patient:f.get("patient"),duration:f.get("duration"),content:f.get("content"),doctor:currentUser.name};if(id)data.prescriptions[data.prescriptions.findIndex(p=>p.id===id)]=o;else data.prescriptions.unshift(o);save();closeModal();render();toast("Ordonnance fictive enregistrée")}
function deletePrescription(id){if(confirm("Supprimer cette ordonnance fictive ?")){data.prescriptions=data.prescriptions.filter(p=>p.id!==id);save();render();toast("Ordonnance supprimée")}}
function printPrescription(id){
let p=data.prescriptions.find(x=>x.id===id),w=window.open("","_blank");
w.document.write(`<html><head><title>Ordonnance fictive</title><style>body{font-family:Arial;padding:50px}h1{margin-bottom:5px}.box{border:1px solid #ddd;padding:20px;margin-top:30px}footer{margin-top:80px;color:#777}</style></head><body><h1>Cabinet Médical Pro</h1><p>Ordonnance — SIMULATION</p><p><b>Patient :</b> ${esc(p.patient)}</p><p><b>Date :</b> ${fmt(p.date)}</p><div class="box">${esc(p.content).replace(/\n/g,"<br>")}<br><br><b>Durée :</b> ${esc(p.duration)}</div><footer>Médecin : ${esc(p.doctor)}<br>Document fictif sans valeur médicale.</footer><script>window.print()</script></body></html>`);w.document.close()
}

function examModal(){
modal("Ajouter un examen fictif",`<form onsubmit="saveExam(event)"><div class="form-grid">
<div class="field full"><label>Patient</label><select name="patient">${data.patients.map(p=>`<option>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div>
<div class="field"><label>Type d'examen</label><select name="type"><option>Analyse sanguine</option><option>Test fictif</option><option>Radiographie fictive</option><option>Échographie fictive</option><option>Autre</option></select></div>
<div class="field"><label>Date</label><input name="date" type="date" value="${today()}"></div>
<div class="field full"><label>Résultat fictif</label><textarea name="result"></textarea></div></div>
<div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Ajouter</button></div></form>`)
}
function saveExam(e){e.preventDefault();let f=new FormData(e.target);data.exams.unshift({id:uid(),patient:f.get("patient"),type:f.get("type"),date:f.get("date"),result:f.get("result"),doctor:currentUser.name});save();closeModal();render();toast("Examen ajouté")}
function deleteExam(id){if(confirm("Supprimer cet examen fictif ?")){data.exams=data.exams.filter(x=>x.id!==id);save();render();toast("Examen supprimé")}}

function documentModal(){
modal("Ajouter un document fictif",`<form onsubmit="saveDocument(event)"><div class="form-grid">
<div class="field full"><label>Patient</label><select name="patient">${data.patients.map(p=>`<option>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div>
<div class="field"><label>Nom du document</label><input name="name" placeholder="Compte-rendu fictif" required></div><div class="field"><label>Catégorie</label><select name="category"><option>Compte-rendu</option><option>Courrier</option><option>Résultat</option><option>Autre</option></select></div></div>
<div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Ajouter</button></div></form>`)
}
function saveDocument(e){e.preventDefault();let f=new FormData(e.target);data.documents.unshift({id:uid(),date:today(),patient:f.get("patient"),name:f.get("name"),category:f.get("category")});save();closeModal();render();toast("Document ajouté")}
function deleteDocument(id){if(confirm("Supprimer ce document fictif ?")){data.documents=data.documents.filter(x=>x.id!==id);save();render();toast("Document supprimé")}}
function resetData(){if(confirm("Réinitialiser toutes les données fictives du navigateur ?")){localStorage.removeItem(KEY);render();toast("Données réinitialisées")}}
render();
