const USERS=[{id:"raphael",name:"Raphaël",role:"Médecin"},{id:"jade",name:"Jade",role:"Médecin"},{id:"victoria",name:"Victoria",role:"Médecin"}];
const KEY="cabinetMedicalProData",SESSION="cabinetMedicalProSession";
const today=()=>new Date().toISOString().slice(0,10);
const demo={patients:[{id:"p1",first:"Lucas",last:"Martin",birth:"2012-04-12",phone:"06 00 00 00 00",blood:"O+",allergies:"Aucune connue",history:"Aucun antécédent fictif",notes:"Démonstration."},{id:"p2",first:"Emma",last:"Bernard",birth:"2011-09-03",phone:"06 11 11 11 11",blood:"A+",allergies:"Pollen",history:"Asthme fictif",notes:"Démonstration."}],appointments:[{id:"a1",date:today(),time:"09:00",patient:"Lucas Martin",reason:"Consultation de suivi",doctor:"Raphaël"},{id:"a2",date:today(),time:"10:00",patient:"Emma Bernard",reason:"Contrôle",doctor:"Jade"}],consultations:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||demo,currentUser=null,page="dashboard";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const fmt=d=>d?new Date(d+"T12:00").toLocaleDateString("fr-FR"):"—";
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2000)}
function render(){currentUser=USERS.find(u=>u.id===localStorage.getItem(SESSION));if(!currentUser)return loginScreen();document.getElementById("app").innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">✚ <span>Cabinet Médical Pro</span><small>SIMULATION • DONNÉES FICTIVES</small></div><nav class="nav">${nav("dashboard","⌂","Tableau de bord")}${nav("patients","👥","Patients")}${nav("appointments","▣","Rendez-vous")}${nav("consultations","🩺","Consultations")}</nav><button class="logout" onclick="logout()">↪ <span>Déconnexion</span></button></aside><main class="main"><header class="topbar"><div><h1>${titles[page]}</h1><div class="sub">Mode simulation médicale</div></div><div class="profile"><div class="avatar">${currentUser.name[0]}</div><div><b>${esc(currentUser.name)}</b><div class="sub">${currentUser.role}</div></div></div></header><div id="content"></div></main></div>`;pageRender()}
const titles={dashboard:"Tableau de bord",patients:"Patients",appointments:"Rendez-vous",consultations:"Consultations"};
function nav(id,i,l){return `<button class="${page===id?"active":""}" onclick="go('${id}')">${i} <span>${l}</span></button>`}
function loginScreen(){document.getElementById("app").innerHTML=`<div class="login"><div class="login-card"><div class="logo">✚</div><h1>Cabinet Médical Pro</h1><p class="sub">Logiciel de cabinet médical — simulation pour votre jeu.</p><div class="notice">⚠️ Données entièrement fictives et conservées uniquement dans ce navigateur.</div><b>Qui est le médecin ?</b><div class="users">${USERS.map(u=>`<button class="user-btn" onclick="login('${u.id}')"><div class="avatar">${u.name[0]}</div><div><b>${u.name}</b><div class="sub">${u.role}</div></div></button>`).join("")}</div></div></div>`}
function login(id){localStorage.setItem(SESSION,id);page="dashboard";render();toast("Connexion réussie")}
function logout(){localStorage.removeItem(SESSION);render()}
function go(p){page=p;render()}
function pageRender(){let c=document.getElementById("content");c.innerHTML=page==="dashboard"?dashboard():page==="patients"?patients():page==="appointments"?appointments():consultations()}
function dashboard(){let ap=data.appointments.filter(a=>a.date===today());return `<div class="grid"><div class="card"><div class="stat-label">Patients enregistrés</div><div class="stat-value">${data.patients.length}</div></div><div class="card"><div class="stat-label">Rendez-vous aujourd'hui</div><div class="stat-value">${ap.length}</div></div><div class="card"><div class="stat-label">Consultations</div><div class="stat-value">${data.consultations.length}</div></div><div class="card"><div class="stat-label">Médecin connecté</div><div class="stat-value" style="font-size:22px">${esc(currentUser.name)}</div></div></div><div class="section"><div class="section-head"><h2>Rendez-vous du jour</h2><button class="btn" onclick="go('appointments')">Voir l'agenda</button></div><div class="card table-wrap">${ap.length?apptTable(ap):'<div class="empty">Aucun rendez-vous aujourd’hui.</div>'}</div></div><div class="section"><div class="grid" style="grid-template-columns:repeat(3,1fr)"><div class="card"><h3>Nouveau patient</h3><p class="sub">Créer un dossier fictif.</p><button class="btn" onclick="patientModal()">Créer</button></div><div class="card"><h3>Nouvelle consultation</h3><p class="sub">Enregistrer une consultation.</p><button class="btn" onclick="consultModal()">Ouvrir</button></div><div class="card"><h3>Nouveau rendez-vous</h3><p class="sub">Ajouter à l’agenda.</p><button class="btn" onclick="apptModal()">Ajouter</button></div></div></div>`}
function patients(){return `<div class="section-head"><p class="sub">Dossiers fictifs du cabinet</p><div class="actions"><input id="search" class="search" placeholder="Rechercher..." oninput="filterPatients()"><button class="btn" onclick="patientModal()">+ Nouveau patient</button></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Naissance</th><th>Téléphone</th><th>Allergies</th><th></th></tr></thead><tbody id="rows">${patientRows(data.patients)}</tbody></table></div>`}
function patientRows(a){return a.length?a.map(p=>`<tr><td><b>${esc(p.first)} ${esc(p.last)}</b></td><td>${fmt(p.birth)}</td><td>${esc(p.phone||"—")}</td><td>${esc(p.allergies||"—")}</td><td><button class="btn secondary" onclick="openPatient('${p.id}')">Ouvrir</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Aucun patient.</td></tr>`}
function filterPatients(){let q=document.getElementById("search").value.toLowerCase();document.getElementById("rows").innerHTML=patientRows(data.patients.filter(p=>(p.first+" "+p.last).toLowerCase().includes(q)))}
function appointments(){return `<div class="section-head"><p class="sub">Agenda fictif du cabinet</p><button class="btn" onclick="apptModal()">+ Nouveau rendez-vous</button></div><div class="card table-wrap">${apptTable(data.appointments)}</div>`}
function apptTable(a){return `<table class="table"><thead><tr><th>Date</th><th>Heure</th><th>Patient</th><th>Motif</th><th>Médecin</th></tr></thead><tbody>${[...a].sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).map(x=>`<tr><td>${fmt(x.date)}</td><td><b>${esc(x.time)}</b></td><td>${esc(x.patient)}</td><td>${esc(x.reason)}</td><td><span class="badge">${esc(x.doctor)}</span></td></tr>`).join("")}</tbody></table>`}
function consultations(){return `<div class="section-head"><p class="sub">Historique des consultations fictives</p><button class="btn" onclick="consultModal()">+ Nouvelle consultation</button></div><div class="card table-wrap">${data.consultations.length?`<table class="table"><thead><tr><th>Date</th><th>Patient</th><th>Motif</th><th>Température</th><th>Médecin</th></tr></thead><tbody>${data.consultations.map(c=>`<tr><td>${fmt(c.date)}</td><td><b>${esc(c.patient)}</b></td><td>${esc(c.reason)}</td><td>${esc(c.temp||"—")} °C</td><td>${esc(c.doctor)}</td></tr>`).join("")}</tbody></table>`:'<div class="empty">Aucune consultation enregistrée.</div>'}</div>`}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`)}
function closeModal(){document.getElementById("modal")?.remove()}
function patientModal(){modal("Nouveau patient",`<form onsubmit="createPatient(event)"><div class="form-grid"><div class="field"><label>Prénom</label><input name="first" required></div><div class="field"><label>Nom</label><input name="last" required></div><div class="field"><label>Date de naissance</label><input name="birth" type="date" required></div><div class="field"><label>Téléphone</label><input name="phone"></div><div class="field"><label>Groupe sanguin</label><select name="blood"><option>Inconnu</option><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option><option>O+</option><option>O-</option></select></div><div class="field"><label>Allergies fictives</label><input name="allergies" placeholder="Aucune connue"></div><div class="field full"><label>Antécédents fictifs</label><textarea name="history"></textarea></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Créer le dossier</button></div></form>`)}
function createPatient(e){e.preventDefault();let f=new FormData(e.target);data.patients.push({id:crypto.randomUUID(),first:f.get("first"),last:f.get("last"),birth:f.get("birth"),phone:f.get("phone"),blood:f.get("blood"),allergies:f.get("allergies"),history:f.get("history"),notes:f.get("notes")});save();closeModal();render();toast("Patient ajouté")}
function openPatient(id){let p=data.patients.find(x=>x.id===id);modal("Dossier patient",`<div class="patient-head"><div class="big-avatar">${esc((p.first[0]||"")+(p.last[0]||""))}</div><div><h2 style="margin:0">${esc(p.first)} ${esc(p.last)}</h2><div class="sub">Patient fictif • né(e) le ${fmt(p.birth)}</div></div></div><div class="detail-grid"><div class="detail"><span>Téléphone</span>${esc(p.phone||"—")}</div><div class="detail"><span>Groupe sanguin</span>${esc(p.blood||"—")}</div><div class="detail"><span>Allergies</span>${esc(p.allergies||"—")}</div><div class="detail"><span>Antécédents</span>${esc(p.history||"—")}</div><div class="detail"><span>Notes</span>${esc(p.notes||"—")}</div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fermer</button><button class="btn" onclick="closeModal();consultModal('${p.id}')">Nouvelle consultation</button></div>`)}
function apptModal(){modal("Nouveau rendez-vous",`<form onsubmit="createAppt(event)"><div class="form-grid"><div class="field full"><label>Patient</label><select name="patient" required>${data.patients.map(p=>`<option>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div><div class="field"><label>Date</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>Heure</label><input name="time" type="time" value="14:00" required></div><div class="field"><label>Médecin</label><select name="doctor">${USERS.map(u=>`<option>${u.name}</option>`).join("")}</select></div><div class="field"><label>Motif</label><input name="reason" required></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Ajouter</button></div></form>`)}
function createAppt(e){e.preventDefault();let f=new FormData(e.target);data.appointments.push({id:crypto.randomUUID(),patient:f.get("patient"),date:f.get("date"),time:f.get("time"),doctor:f.get("doctor"),reason:f.get("reason")});save();closeModal();render();toast("Rendez-vous ajouté")}
function consultModal(pid=""){modal("Nouvelle consultation",`<form onsubmit="createConsult(event)"><div class="form-grid"><div class="field full"><label>Patient</label><select name="patient" required>${data.patients.map(p=>`<option ${p.id===pid?"selected":""}>${esc(p.first+" "+p.last)}</option>`).join("")}</select></div><div class="field full"><label>Motif</label><input name="reason" placeholder="Ex. contrôle, douleur..." required></div><div class="field"><label>Température (°C)</label><input name="temp" type="number" step=".1"></div><div class="field"><label>Pouls (bpm)</label><input name="pulse" type="number"></div><div class="field"><label>Tension</label><input name="bp" placeholder="120/80"></div><div class="field"><label>Saturation (%)</label><input name="sat" type="number"></div><div class="field full"><label>Symptômes / observations fictives</label><textarea name="notes"></textarea></div><div class="field full"><label>Conclusion fictive</label><textarea name="conclusion"></textarea></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Annuler</button><button class="btn">Enregistrer</button></div></form>`)}
function createConsult(e){e.preventDefault();let f=new FormData(e.target);data.consultations.unshift({id:crypto.randomUUID(),date:today(),patient:f.get("patient"),reason:f.get("reason"),temp:f.get("temp"),pulse:f.get("pulse"),bp:f.get("bp"),sat:f.get("sat"),notes:f.get("notes"),conclusion:f.get("conclusion"),doctor:currentUser.name});save();closeModal();render();toast("Consultation enregistrée")}
render();